language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

sudo: false

before_script:
    - yes '' | pecl install -f apcu
    - composer install

script:
    - composer build

after_success:
    - travis_retry composer dist