language: php

php:
    - 7.3
    - 7.4
    - 8.0

sudo: false

before_script:
    - yes '' | pecl install -f apcu
    - composer install

script:
    - composer build

after_success:
    - travis_retry composer dist